### ISSUE TITLE
The installation failed (Mac OS Mojave)

### ISSUE THREAD

**Issue by LucaTucciarone** [rmacoslib/r-macos-rtools#12]
I guess the installer has to be updated for Mac OS Mojave. 
It gets sucked in Running package scripts for 5+ min and then fails the installation. 
It just suggest to contact the developer. Could you help me?

**Comment by philophthalmus** [comment]
I have the same issue. It would be great if you could address this.

**Comment by LucaTucciarone** [comment]
I’m sorry but I just found a workaround to my problem (and your tools was the solution).
I mean, my problem was the following:

https://stackoverflow.com/questions/53030392/cannot-install-any-package-in-r-mac-os-mojave
Thanks to answer, 
Luca

**Comment by coatless** [comment]
@LucaTucciarone & @philophthalmus thanks for the heads up. We should have a fix sometime today or tomorrow.

**Comment by aminadibi** [comment]
I have the same issue :(
