### ISSUE TITLE
Mac-OS installer not working and I don't have Mojave OS

### ISSUE THREAD

**Issue by hwaterhouse** [rmacoslib/r-macos-rtools#13]
Hi, 
I tried downloading the R toolchain for mac OS high sierra and it failed. I have the updated version of RStudio. Not sure why it won't work.

Thanks,
Hannah

**Comment by coatless** [comment]
@hwaterhouse thanks for the heads up. This issue was reported in #12. We should have a fix sometime tomorrow.
