### ISSUE TITLE
Adding path to gfortran to .Renviron

### ISSUE THREAD

**Issue by wloo** [rmacoslib/r-macos-rtools#21]
Thanks for writing this easy to use installer!

I upgraded R from 3.5.2 to 3.6.1 and used it to update a couple packages requiring clang and gfortran (data.table 1.12.4 and KernSmooth 2.23.16, respectively). However, by default the path to the gfortran installation was not added to the .Renviron file, and thus I was still getting the error "gfortran not found". 

Adding it to the .Renviron file fixed this. It may be helpful to include writing this path to the .Renviron file as a default along with clang.

**Comment by coatless** [comment]
Hmm, the path to `gfortran` shouldn't be needed. We're retrieving and installing `gfortran6.1.0`, which is used to compile the _R_ binary version of CRAN. 

Could I see your `~/.R/Makevars`?

**Comment by wloo** [comment]
I figured it might be an error on my end. Here's the contents of `~/.R/Makevars`
```
# clang: start
CFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
CCFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
CXXFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
# clang: end
```

**Comment by coatless** [comment]
Not needed in the end. c.f. #30
