### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by bholden7** [rmacoslib/r-macos-rtools#23]
I can't install on my mac: Apple can't check for malicious software.

**Comment by coatless** [comment]
Few questions:

1. Can I see a screenshot of the installer?
2. Are you connected to the internet?
3. What operating system are you using?

**Comment by bholden7** [comment]
Hi, thanks for getting back.
Yes, connected to Internet.
OS is Catalina.

Not sure how to get screenshot of installer.
I installed Xcode last week, because I needed it to install/run an R package ‘Stan’ (which, in turn, is needed for the package ‘brms’). Which is odd to me because I’ve run ‘rstanarm’ previously (which requires ‘rstan') with no problems and no compiler.

Anyway, please advise. Many thanks.

**Edit by @coatless :** Removed personal information.

**Comment by coatless** [comment]
Can you take a screenshot with Shift-Command-5 or Shift-Command-3?

c.f. https://support.apple.com/en-us/HT201361

**Comment by bholden7** [comment]
**Edit by @coatless :** Removed personal information.

**Comment by coatless** [comment]
@bholden7 the screenshot doesn't look like it came through via e-mail. Could you post it here: https://github.com/rmacoslib/r-macos-rtools/issues/23

Thanks!

**Comment by bholden7** [comment]
![image](https://user-images.githubusercontent.com/44203517/68608443-ec007780-0480-11ea-8521-35520509e8a0.png)

**Comment by bholden7** [comment]
This is the error message I get when trying to run code:

Error in compileCode(f, code, language = language, verbose = verbose) : Compilation ERROR, function(s)/method(s) not created! clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot] In file included from file31be783b39fa.cpp:8: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/src/stan/model/model_header.hpp:4: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math.hpp:4: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/mat.hpp:4: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/core.hpp:4: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/include/stan/math/rev/core/autodiffstackstorage.hpp:4: In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/StanHeaders/i
Error in sink(type = "output") : invalid connection

**Comment by coatless** [comment]
@bholden7 thanks! I'll try to issue a fix later today. Okay?

**Comment by bholden7** [comment]
Thanks very much.


Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227

**Comment by mikekaminsky** [comment]
Just ran into this same issue -- let me know if I can help!

**Comment by coatless** [comment]
Please try out the latest version here: https://github.com/rmacoslib/r-macos-rtools/releases/tag/v3.1.0

**Comment by mikekaminsky** [comment]
I got the same error :( 
![Screen Shot 2019-11-13 at 9 32 10 PM](https://user-images.githubusercontent.com/5394529/68824644-2a528e00-065d-11ea-9e21-d5aa9263d825.png)

**Comment by coatless** [comment]
What happens when you:

> Right click on the installer and click open from the menu?

**Comment by mikekaminsky** [comment]
Same response

**Comment by coatless** [comment]
You should get this: 

![Open installer...](https://user-images.githubusercontent.com/833642/68826173-5f151400-0662-11ea-8a57-418f88f41ea3.png)

Clicking open should take you in to the installer. 

I'm wondering if the dev key needs to be refreshed...

**Comment by mikekaminsky** [comment]
:shrug: i'm definitely not getting that! I wish I could be of more help
here but I'm a little out of my depth on this...

**Comment by coatless** [comment]
@mikekaminsky This will take a bit longer. Apologies in advance... 

We need to notarize the installer application now...

**Comment by mikekaminsky** [comment]
Got it -- I actually was able to get unblocked with the xcode compiler, so
this isn't a pressing issue for me. Happy to keep testing as long as it's
helpful :)

Thank YOU for being such a responsive maintainer.
