### ISSUE TITLE
Notify users that a new .Renviron is being created rather than appended to

### ISSUE THREAD

**Issue by joranE** [rmacoslib/r-macos-rtools#27]
I may not have been paying attention while the installer was running and hence missed a notification or comment about this, but it tripped me up for a bit.

Specifically, I somehow missed that my old .Renviron was moved to .Renviron.bck and a new file created. It broke some other stuff that I wasn't expecting and it took me a while to piece together that this is what had happened.

With such an easy to use (and appreciated!) tool like this with everything packaged up into a macOS installer, it might make sense to be more explicit about what's going to happen to the contents of their .Renviron file. Again, it's possible I missed it because I was just clicking through the installer, but that might be the sort of user behavior you're going to see with a tool like this.

Thanks again for building this!

**Comment by coatless** [comment]
@joranE sorry for the headache. 

I'll clean up the verbiage on the `README.md` and within the main splash screen to emphasize we're replacing the files vs. doing line substitutions.
