### ISSUE TITLE
set PATH for fortran

### ISSUE THREAD

**Issue by runehaubo** [rmacoslib/r-macos-rtools#30]
Thanks a lot for creating this tool! 

I found it necessary to add `/usr/local/gfortran/bin` to the PATH in `.Renviron` in order to compile packages containing fortran code. Before adding that to the path I got 

    make[1]: gfortran: No such file or directory

This was on macOS Catalina version 10.15.2 with a fresh R-devel 4.0.0 while attempting to install package `ucminf` from CRAN.
It is entirely possible that I'm just missing something as I'm in over my head here, but thought I'd mention it.

Cheers
Rune

**Comment by coatless** [comment]
@runehaubo thanks for the heads up. I'll look into it more. (Self note: one instance prior #21).

Right now, the `rtools` variant is slated to work on the latest patch release (e.g. R v3.6.2). That said, R 4.0.0 will be using `clang8`, which is one version higher than what is provided now (`clang7`).

**Comment by coatless** [comment]
As R 4.0.0 was released in April, the main change was a standalone `clang` is no longer used. The detection for `gfortran` increased greatly as well. So, we're going to avoid adding `gfortran`'s location to the `PATH`.
