### ISSUE TITLE
The Latest Package Cannot Open

### ISSUE THREAD

**Issue by obinnaonwuchekwa** [rmacoslib/r-macos-rtools#39]
My MAC tells me it cannot open the package as it is unable to scan it for malicious software. It says the package needs to be updated.

**Comment by ammadrigal** [comment]
Hello, I just ran into the same issue. I am in MACOS Catalina.
Any ideas? 
I am trying to install a package from GitHub using either devtools or remote within R Studio.
I hadn't tried that after I upgraded to Catalina some weeks ago. Before I didn't have any problems.

I read that the solution was to use your package and I'm really hoping to use it.
Here the screen: There is no "Open / Cancel" option, just the "OK"

<img width="420" alt="Screenshot 2020-06-11 at 19 50 41" src="https://user-images.githubusercontent.com/8194297/84452966-e4729e00-ac1c-11ea-94f1-2bdac1ee8f9b.png">

**Comment by coatless** [comment]
Right click, select open from the context menu, and then you should be able to install.

**Comment by ammadrigal** [comment]
Thanks! I'll try a bit later today. Just confirming, this is not R-version dependent, correct?
Im in R 3.5.3, thinking in going soon to 4, but haven't upgraded R yet. 
Will this identify my R version and correct accordingly? Or do I need to upgrade R to 4, before I use this tool?

Thanks very much for your fast replies:)

Ana Maria

**Comment by coatless** [comment]
The latest version is keyed to R 4.0.0. Due to how frequently _R_ changes the toolchain and the different kind of macOS operating systems, it's easier to freeze a version at each version. If you're just getting into compiled code, you probably want to use R 4.0.0.

This installer mainly attempts to automate:

https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

**Comment by mattwarkentin** [comment]
If you hold the `control` button on your keyboard when left-clicking the .pkg installer, it should let you proceed with the toolchain installer.

**Comment by paprika920** [comment]
Hi, 
I got it opened!
But the installation failed. I am on macOS Big Sur 11.0.1.
I took a screen shot:


<img width="986" alt="Screen Shot 2020-11-27 at 11 12 46 AM" src="https://user-images.githubusercontent.com/39174724/100407236-cf8ea780-30a2-11eb-9415-973958ff6cc7.png">

**Comment by pleiby** [comment]
Now a year later, Exactly same failure behavior as "paprika920 commented on Nov 26, 2020".
`macos-rtools-4.0.0.pkg` fails with the above msg "The Installation Failed."
R version 4.1.1. Mac OS Big Sur 11.5.2

Can we install toolchain needed for rstan in Mac OS Big Sur? Thx

**Comment by jmlee-de** [comment]
Same issue: installer `macos-rtools-4.0.0.pkg ` fails with MacOS Monteray 12.0.1 (as of Feb 2022)
Correction planned?  Workaround?

**Comment by hcwi** [comment]
The same issue here with MacOS Monterey 12.1.
```
> ...
> package_script_service[30806]: ./postinstall: [init] Downloading the appropriate gfortran package ...
> package_script_service[30806]: ./postinstall: [error] Bad version supplied ...
> ...
```

**Comment by hmcmonagle** [comment]
Looks like I'm joining the club of "The Installation Failed." I have R version 4.1.1, Mac OS Big Sur 11.4. Me error message looks like the one from @paprika920. I'll keep looking for workarounds and report back if I find something!

edit: I updated to Monterey 12.0.1 an am still receiving the same error message. 
<img width="616" alt="Screen Shot 2022-04-11 at 4 49 42 PM" src="https://user-images.githubusercontent.com/43573863/162851180-c8862841-7322-4336-b96e-d7ce2d8b6c3f.png">

**Comment by mattysimonson** [comment]
Same "The installation failed" message here with Mac OS Monterrey 12.2.1

**Comment by daaronr** [comment]
Same message, also with Mac OS Monterrey 12.2.1

**Comment by xorange** [comment]
Same on Monterrey 12.5, with release 4.0.0

Also I'm suggesting using the 👍ThumbUp icon (in Top-Right button in each comment) to report on the same issue, so that every one in thread would not get a notification spam each time a similar response came up.

**Comment by xorange** [comment]
After a quick scan, It seemed that the macos pkg only contains a shell script.

git clone this repo and run `sh scripts/postinstall` should have the same effect as installing the pkg.

My Environment:

> Same on Monterrey 12.5, with release 4.0.0

reported that gfortran version is not found, therefore the failure.

I think for whomever failed to install, just goto [gfortran-for-macOS's release page](https://github.com/fxcoudert/gfortran-for-macOS/releases) and find one suitable for you Mac, and You(We) are good to go.

Update:

I've succeeded with `cmdstanr::install_cmdstan()` in R Studio, which calls clang to compile some cpp file. So I'm guessing (new to R, all I could do now is guessing) "C++ toolchain in R" is just xcode environment. And my environment is good to go.

* hint: If you could build C++ with CMake on your Mac, you're probably good to go
* hint: Download a proper [gfortran-for-macOS's release](https://github.com/fxcoudert/gfortran-for-macOS/releases)
* Feel free to correct me if I'm wrong. And DO correct me if so.

**Comment by xorange** [comment]
Referring to: https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

I'm gaining confidence that my instructions are correct.

If you have no idea for what "toolchain", "CMake", "environment" means, just follow these steps:

> Open the Terminal from /Applications/Utilities/
> Type the following into Terminal

> `xcode-select --install`
> Press “Install”

> Verify installation by typing into terminal:
> `gcc --version`

**Comment by coatless** [comment]
**This installer has been superceded by the [{macrtools}](https://github.com/coatless-mac/macrtools) _R_ package, which automatically installs and configures the _R_ toolchain for compiled code on macOS.**

**Please do not use this installer package as it is notably out of date.**
