### ISSUE TITLE
helloworld cpp gives same errors as compiling R packages

### ISSUE THREAD

**Issue by GeraldCNelson** [rmacoslib/r-macos-rtools#41]
Here's the program from the coatless prof

```
#include <RcppArmadillo.h>   

// [[Rcpp::depends(RcppArmadillo)]]

// [[Rcpp::export]]
void hello_world() {
  Rcpp::Rcout << "Hello World!" << std::endl;  
}

// After compile, this function will be immediately called using
// the below snippet and results will be sent to the R console.

/*** R
hello_world() 
*/
```

Here's the beginning of the error messages

> clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include   -I"/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include" -I"/Users/gcn/Documents/workspace/ISIMIPData/temp" -I/usr/local/include   -fPIC  -Wall -g -O2  -c helloworld.cpp -o helloworld.o
> In file included from helloworld.cpp:1:
> In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
> In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:26:
> In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/RcppCommon.h:29:
> In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
> In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
> In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:304:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:760:41: error: no member named 'fabsf' in the global namespace
> abs(float __lcpp_x) _NOEXCEPT {return ::fabsf(__lcpp_x);}
>                                       ~~^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:764:42: error: no member named 'fabs' in the global namespace; did you mean 'abs'?
> abs(double __lcpp_x) _NOEXCEPT {return ::fabs(__lcpp_x);}
>                                        ~~^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:760:1: note: 'abs' declared here
> abs(float __lcpp_x) _NOEXCEPT {return ::fabsf(__lcpp_x);}
> ^
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:768:47: error: no member named 'fabsl' in the global namespace
> abs(long double __lcpp_x) _NOEXCEPT {return ::fabsl(__lcpp_x);}

And the final error message is 

> make: *** [helloworld.o] Error 1
> Error in Rcpp::sourceCpp("temp/helloworld.cpp") : 
>   Error 1 occurred building shared library.

**Comment by coatless** [comment]
@GeraldCNelson please keep it to one issue ticket #40 

I'm going to close this one.
