### ISSUE TITLE
Make it clear for which macOS versions this works

### ISSUE THREAD

**Issue by dfsp-spirit** [rmacoslib/r-macos-rtools#43]
Thanks for the great installer. I just wondered for which macOS versions it works.

We recently upgraded a machine in our lab to macOS Monterey, and since then compiling R packages does no longer work. Is this installer supposed to work under Monterey? Or is it independent of the macOS version?

Thanks again,

Tim

**Comment by brepowers** [comment]
I am having a similar issues as Tim. I have mac OS Monterey and I can get to the very last step in the installation but then it will tell me the installation failed. I've down loaded the r-macos-rtools a number of times and tried installing it several time and I still get installation fails.

**Comment by miguellacerda** [comment]
Same issue as @brepowers on macOS Monterey.

**Comment by LeoSokolovic** [comment]
I am also experiencing the same issue as @brepowers on macOS Monterey.

**Comment by huyenntt53** [comment]
I am trying to install this on macOS Monterey ver 12, I got to the last step of installation but it failed several times. Anyone knows how to fix this problem?

**Comment by droach7** [comment]
I am also having this issue on Monterey ver 12.3. Would love to know how to fix this issue.

**Comment by wdefreitas** [comment]
same issue

**Comment by madelinecraft** [comment]
I'm experiencing the same issue.

**Comment by rich-ramsey** [comment]
I have the same issue. Any help or advice would be appreciated.

**Comment by rich-ramsey** [comment]
To follow-up on this thread, the installer didn't work for mac os monterey, but follwoing these instructions did work for me:
https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

Thanks to The Coatless Professor!

Regards,
Rich

**Comment by madelinecraft** [comment]
I fixed the problem by installing Xtools via the App Store on my Mac. It was pretty simple, but did take a long time to install.

**Comment by lizzieinvancouver** [comment]
Or it may be a false positive? Hard to know in the end as I did a few things along the way ... but I got Rstan to work by forging ahead and assuming the installer actually worked (though it said it failed). See [here](https://discourse.mc-stan.org/t/friendly-mac-c-installer-does-not-work-for-me-whats-another-option/27272/4). Running OS 12.3.1, M1 chip.

**Comment by xorange** [comment]
I may have a solution for this. See #39 

In short, "just goto [gfortran-for-macOS's release page](https://github.com/fxcoudert/gfortran-for-macOS/releases) and find one suitable for you Mac"

C++ toolchain in R is just xcode environment, if you could do C++ dev already, it's probably fine

**Comment by coatless** [comment]
**This installer has been superceded by the [{macrtools}](https://github.com/coatless-mac/macrtools) _R_ package, which automatically installs and configures the _R_ toolchain for compiled code on macOS.**

**Please do not use this installer package as it is notably out of date.**
