### ISSUE TITLE
Installation failed on MacBook Air M2

### ISSUE THREAD

**Issue by Shwoobly** [rmacoslib/r-macos-rtools#44]
The macOS-rtools-4.0.0.pkg failed to install on my MacBook Air M2. See image.
I have installed R 4.2.2 GUI 1.79 High Sierra build (intel).
what to do?

<img width="620" alt="Installation failed" src="https://user-images.githubusercontent.com/49795920/219495468-369ed426-0d4d-4c35-9ab7-f4da973fbfa3.png">

**Comment by coatless** [comment]
**This installer has been superceded by the [{macrtools}](https://github.com/coatless-mac/macrtools) _R_ package, which automatically installs and configures the _R_ toolchain for compiled code on macOS.**

**Please do not use this installer package as it is notably out of date.**
